apiVersion: v1
kind: Service
metadata:
  name: devops-playground-service
spec:
  type: NodePort
  selector:
    app: devops-playground
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
